---
title: "Estadística I & Estadística Descriptiva"
subtitle: ""
author: "[Daniel Franzani](https://dfranzani.github.io/website/principal/home.html)"
description: >
  Curso básico de Estadística para ingeniería.
date: "Actualizado al `r format(Sys.Date(), '%d-%m-%Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: refs.bib
csl: apa-annotated-bibliography.csl # Gitbook
biblio-style: apalike # Latex
url: 'https://dfranzani.github.io/Estadistica_I/'
link-citations: yes
github-repo: "Dfranzani/Estadistica_I"
fontsize: 11pt
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
options(tinytex.engine_args = '-shell-escape') # Minted indent
#rmarkdown::find_pandoc(cache = TRUE, dir = "/usr/bin", version = NULL) # Pandoc versión (referencias y tablas)
library(ggplot2)
library(kableExtra)
# library(gridExtra)
options(kableExtra.html.bsTable = T)

# screenshot HTML widgets
if (is.null(webshot:::find_phantom())) webshot::install_phantomjs()
```


```{r echo = F, results='asis'}
if (knitr::is_html_output()){
  cat("# Presentación {-}","\n","El documento Estadística I es el primero de una serie de dos, el cual tiene un enfoque práctico con énfasis en el estudio descriptivo de datos. Este primer documento aborda los tópicos de gráficos descriptivos, medidas de resumen, funciones de probabilidad y distribuciones muestrales, haciendo uso del entorno de software R.","\n","\n","[Enlace al documento del segundo curso de Estadística: Estadística II & Inferencia Estadística](https://dfranzani.github.io/Estadistica_II/).")
}
```


```{r echo = F, results='asis'}
if (knitr::is_html_output()){
   cat("# Talleres de práctica {-}", "\n", "A continuación, se muestra una lista de los talleres disponibles:", "\n", "\n")
   talleres = list.files(path = "material/talleres/Talleres de practica")
   talleres_pruebas = talleres[grepl(".pdf", talleres) & grepl("prueba", talleres)]
   taller_examen = talleres[grepl(".pdf", talleres) & grepl("examen", talleres)]
   talleres = talleres[grepl(".pdf", talleres) & !grepl("examen", talleres) & !grepl("prueba", talleres)]
   
   link = function(taller, tipo){
      if(length(taller) != 0){
         taller = taller[order(taller)]
         if(tipo == "Taller de práctica Examen"){
            taller = paste0("[", tipo, "](material/talleres/Talleres de practica/", taller, ")")
         } else{
            taller = paste0("[", tipo, 1:length(taller), "](material/talleres/Talleres de practica/", taller, ")")
         }
      }
      return(taller)
   }
   
   talleres = c(link(talleres, "Taller de práctica "),
                link(talleres_pruebas, "Taller de práctica Evaluación "),
                link(taller_examen, "Taller de práctica Examen"))
   
   cat(" - [Taller introductorio](material/talleres/Taller introductorio/Taller_Introductorio_a_R.ipynb) \n")
   
   if(length(talleres) != 0){
      for (i in 1:length(talleres)) {
         cat(paste(" -", talleres[i]), "\n")
      }
   }
}
```

```{r, echo=FALSE}
# Valor para desplegar los código de carga de bases de datos dependiendo de la salida del documento
if (knitr::is_html_output()){
  code = TRUE
} else {
  code = FALSE
}
```
